/*
 * This source file was generated by the Gradle 'init' task
 */
package com.api.base;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Properties;

public class TestBase {

    protected Properties properties;

    public TestBase() {
        properties = new Properties();
        try {
            properties.load(getClass().getClassLoader().getResourceAsStream("config.properties"));
        } catch (FileNotFoundException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
}
