/*
 * This source file was generated by the Gradle 'init' task
 */
package restapi;

class AppTest {

    public static void main(String[] a) {

        // Reverse a String
        String name = "JaVa";
        char[] nameArray = name.toCharArray();
        for (int index=nameArray.length; index > 0; index--) {
            System.out.print(nameArray[index-1]);
        }
        StringBuilder reversedName = new StringBuilder(name);
        System.out.println("\nReversed Name: " + reversedName.reverse());

        System.out.println("\nLoweCase Name: ");
        for(char c: nameArray) {
            if (Character.isUpperCase(c)) {
            System.out.print(Character.toLowerCase(c));
        } else if (Character.isLowerCase(c)) {
            System.out.print(Character.toUpperCase(c));
        } else {
            System.out.print(c);    
        }
        }
    }
}
